/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportReview.java
 *
 * Created on Apr 19, 2011, 9:15:54 AM
 */

package bahrie.tokobukuapp.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author bahrie
 */
public class ReportReview extends javax.swing.JFrame {

    /** Creates new form ReportReview */
    public ReportReview(JasperPrint jp) {
        initComponents();
        JRViewer jrv=new JRViewer(jp);
        this.setLocationRelativeTo(null);
        this.getContentPane().add(jrv,BorderLayout.CENTER);
        this.setMinimumSize(new Dimension(900, 600));
        this.setPreferredSize(new Dimension(900, 600));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Preview");
        setLocationByPlatform(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
